Repository GEON-PPANG/GEON-PPANG-SERVER, pull requests merged in 2023-07, with the labels that each got.

#16 Feature/#10 건빵집 리스트 조회해라
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDto.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BookmarkRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/CategoryRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
  storage/db-core/src/main/resources/init/h2-schema.sql
Labels: FEAT, euna

#18 [FEAT] 건빵집 상세정보 조회 구현해라
  api/src/main/java/com/org/gunbbang/controller/BakeryController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/MenuResponseDto.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/MenuRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: FEAT, euna

#24 [FEAT] 건빵집에 리뷰 등록해라
  api/src/main/java/com/org/gunbbang/controller/BakeryController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/KeywordNameRequestDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/ReviewRequestDto.java
  api/src/main/java/com/org/gunbbang/controller/ReviewController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Review.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/ReviewRecommendKeyword.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/RecommendKeywordRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRecommendKeywordRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: FEAT, euna

#27 [FEAT] 베스트 건빵집 리스트를 조회하라
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/controller/BookMarkController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/BookMarkRequestDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseBakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BestBakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BookMarkResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberDetailResponseDto.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/BookMarkService.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  common/enum/src/main/java/com/org/gunbbang/MainPurpose.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryCategory.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/BookMark.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Member.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Menu.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Review.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/ReviewRecommendKeyword.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BookmarkRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/MenuRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: FEAT, seungha

#28 [FEAT] 건빵집 작성된 리뷰 조회해라
  api/src/main/java/com/org/gunbbang/controller/BakeryController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/RecommendKeywordNameRequestDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/ReviewRequestDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/RecommendKeywordResponseDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewListResponseDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewResponseDto.java
  api/src/main/java/com/org/gunbbang/controller/ReviewListController.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRecommendKeywordRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: FEAT, euna

#29 [FEAT] 북마크 기능 추가
  api/build.gradle
  api/src/main/java/com/org/gunbbang/controller/BookMarkController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/BookMarkRequestDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BookMarkResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/VO/CurrentMemberVO.java
  api/src/main/java/com/org/gunbbang/service/BookMarkService.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  common/exception/src/main/java/com/org/gunbbang/DoubleBookMarkRequestException.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/BookMark.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BookmarkRepository.java
Labels: FEAT, seungha

#32 [FEAT] 유저 필터칩 변경 기능을 구현하라
  api/src/main/java/com/org/gunbbang/controller/DTO/request/MemberTypesRequestDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberTypesResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/NutrientTypeResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/MemberController.java
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Member.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/MemberRepository.java
Labels: FEAT, seungha

#34 [FEAT] 회원 필터칩 조회 기능을 구현하라
  api/src/main/java/com/org/gunbbang/controller/MemberController.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
Labels: FEAT, seungha

#35 [CHORE] 베스트 컨빵집 조회 api를 베스트 컨텐츠 조회 컨트롤러로 분리하라
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/controller/BestContentController.java
Labels: FEAT, seungha

#37 [FIX] BakeryDetailResponseDto를 BaseBakeryResponseDto를 상속받는 클래스로 수정해라
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BestBakeryListResponseDTO.java
Labels: euna, FIX

#39 [FIX] BakeryListResponseDto를 BaseBakeryResponseDto를 상속받는 클래스로 수정해라
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/controller/BakeryController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDto.java
Labels: euna, FIX

#40 [FEAT] 회원이 남긴 리뷰를 빵집 정보에 기반해 리스트 형태로 데이터를 받을 수 있는 기능을 구현해라
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListReviewedByMemberDto.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BaseDTO/BaseBakeryResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/MemberController.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: FEAT, euna

#45 [FEAT] 건빵집을 이름만으로 조회해라
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakerySearchResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: FEAT, seungha

#46 [CHORE] reviewCount -> resultCoount로 변수명을 변경해라
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
Labels: FEAT, seungha

#48 [FEAT] 북마크한 빵집 조회 api 추가
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java
Labels: FEAT, seungha

#50 [FEAT] CustomUserDetails에서 현재 접속한 회원의 빵유형, 주목적, 영양성분 공개 정보를 가져와라
  README.md
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
  api/src/main/java/com/org/gunbbang/login/CustomUserDetails.java
  api/src/main/java/com/org/gunbbang/login/service/CustomLoginService.java
  api/src/main/java/com/org/gunbbang/util/Security/SecurityUtil.java
Labels: FEAT, seungha

#51 [FEAT] 닉네임 중복 체크 기능을 추가해라
  api/src/main/java/com/org/gunbbang/config/SecurityConfig.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/ValidateNicknameRequestDTO.java
  api/src/main/java/com/org/gunbbang/controller/S3Controller.java
  api/src/main/java/com/org/gunbbang/controller/ValidationController.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
Labels: FEAT, seungha

#55 [FIX] 건빵집 이름으로 조회 시 앞뒤 공백을 무시하라
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
Labels: FEAT, seungha

#57 Feature/#54
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  storage/db-core/src/main/resources/init/h2-schema.sql
Labels: FEAT, seungha

#62 [FEAT] 베스트 건빵집 조회 시 10개 모자랐을 때 랜덤으로 추가로 조회
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: FEAT, seungha

#63 [FIX] 리뷰 키워드 1개밖에 없을 때 다른 한 값은 null로 응답해라
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: seungha, FIX

#65 [FIX] 북마크 추가/취소 flag 변수를 응답에 추가하라
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BookMarkResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BookMarkService.java
Labels: seungha, FIX

#68 [FIX] 건빵집 bakery service 로직에서 bookMark 판별 로직을 분리해라
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
Labels: euna, FIX

#69 [FEAT] 로그백 설정과 로깅용 AOP 기능을 추가하라
  .github/workflows/cd.yml
  .github/workflows/gradle.yml
  api/build.gradle
  api/src/main/java/com/org/gunbbang/AOP/LogInfo.java
  api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java
  api/src/main/java/com/org/gunbbang/AOP/RequestApiInfo.java
  api/src/main/java/com/org/gunbbang/controller/BestContentController.java
  api/src/main/java/com/org/gunbbang/controller/BookMarkController.java
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
  api/src/main/java/com/org/gunbbang/controller/ServerProfileController.java
  api/src/main/java/com/org/gunbbang/controller/ValidationController.java
  api/src/main/resources/logback-spring.xml
  logs/api-error.2023-07-15.gz
  logs/api-error.log
  logs/api.2023-07-15.gz
  logs/api.log
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: FEAT, seungha

#73 [FIX] 운영 환경에서의 로그백 파일 에러를 해결하라
  api/src/main/resources/logback-spring.xml
  logs/api.log
Labels: bug, seungha

#74 [FIX] 건빵집 리스트 조회 기본값일 때 조회 추가해라
  LOG_PATH_IS_UNDEFINED/api-error.log
  LOG_PATH_IS_UNDEFINED/api.log
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/CategoryRepository.java
Labels: euna, FIX

#75 [FIX] 수정된 반영사항에 따라 BaseBakeryEntity 수정 및 관련 api에서 사용되는 ResponseDto 내용 수정해라
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  logs/api.log
Labels: euna, FIX

#78 [FIX] 리뷰 좋아요 선택시 리뷰키워드를 선택하지 않아도 저장되는 로직을 수정해라
  api/src/main/java/com/org/gunbbang/controller/ReviewController.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
Labels: euna, FIX

#89 [FIX] spring-web 의존성을 명시적으로 추가하라
  api/build.gradle
  build.gradle
Labels: seungha, FIX

#93 [FIX] 7/18일자 코드리뷰를 반영해라
  api/src/main/java/com/org/gunbbang/common/CategoryType.java
  api/src/main/java/com/org/gunbbang/controller/AuthController.java
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/controller/ReviewsController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  logs/api-error.2023-07-18.gz
  logs/api-error.log
  logs/api.log
  storage/db-core/src/main/java/com/org/gunbbang/common/RecommendKeywordType.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/NutrientTypeRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: euna, FIX

#94 [FIX] 바인딩 에러에 대해 공통 응답 규격으로 반환하도록 변경하라
  api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
Labels: seungha, FIX

#96 [FIX] 리뷰 키워드 조회 시 한국어 카피로 나가도록 수정하라
  .gitignore
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  common/enum/src/main/java/com/org/gunbbang/RecommendKeyword.java
  logs/api-error.2023-07-15.gz
  logs/api-error.2023-07-16.gz
  logs/api-error.2023-07-18.gz
  logs/api-error.log
  logs/api.2023-07-15.gz
  logs/api.2023-07-17.gz
  logs/api.log
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: seungha, FIX

#100 [FIX] dev에 머지할 때 CI 프로세스를 생략해라
  .github/workflows/gradle.yml
Labels: seungha, FIX

#101 [FIX] 검색어에 빈 문자열 들어왔을 때 빈 response 반환하는 로직을 추가하라
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakerySearchResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/BookMarkService.java
Labels: seungha, FIX

#108 [FIX] 베스트 건빵집 조회 시 빈 리스트 내려가는 버그를 수정해라
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: bug, seungha

#97 [CHORE] CustomLoginService -> CustomUserDetailsService로 이름 변경하라
  api/src/main/java/com/org/gunbbang/config/SecurityConfig.java
  api/src/main/java/com/org/gunbbang/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java
  api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
Labels: seungha, FIX
