Repository GEON-PPANG/GEON-PPANG-SERVER, pull requests merged in 2023-08, with the labels that each got.

#131 [FIX] 북마크하는 api 를 리팩토링하라
  api/src/main/java/com/org/gunbbang/controller/BookMarkController.java
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
  api/src/main/java/com/org/gunbbang/service/BookMarkService.java
  api/src/main/java/com/org/gunbbang/util/mapper/BookMarkMapper.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java
Labels: seungha, FIX

#132 [FIX] 회원 필터칩 및 북마크 모아보기 관련 api 리팩토링
  api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberTypeResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/MemberController.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/util/mapper/MemberTypeMapper.java
  api/src/main/java/com/org/gunbbang/util/mapper/NutrientTypeMapper.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
Labels: seungha, FIX

#134 [FIX] 건빵집 상세보기에 길찾기 url 값 추가해라
  .gitignore
  api/logs/api-error.2023-07-19.gz
  api/logs/api-error.log
  api/logs/api.log
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  logs/api-error.log
  logs/api.2023-07-19.gz
  logs/api.log
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/resources/init/h2-data.sql
  storage/db-core/src/main/resources/init/h2-schema.sql
Labels: euna, FIX

#135 [Refactor] 베스트 컨텐츠 조회 api 리팩토링 및 북마크 여부 제외
  .gitignore
  api/src/main/java/com/org/gunbbang/controller/BestContentController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BestBakeryListResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BestReviewListResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/util/mapper/BakeryMapper.java
  api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java
  api/src/main/resources/logback-spring.xml
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: seungha, FIX

#137 [FIX] Bakery 엔티티에 instagram url 필드 추가해라
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Bakery.java
  storage/db-core/src/main/resources/init/h2-data.sql
  storage/db-core/src/main/resources/init/h2-schema.sql
Labels: euna, FIX

#142 [FEAT] 빵집 이름 검색에 근처 역명/지역명으로 검색해도 해당되는 빵집을 찾을 수 있도록 기능 추가해라
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/specification/BakerySpecifications.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: FEAT, euna

#145 [FIX] 빵집 상세보기 리팩터링
  api/src/main/java/com/org/gunbbang/controller/DTO/response/BakeryDetailResponseDTO.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/util/ConstantVO.java
  api/src/main/java/com/org/gunbbang/util/mapper/BakeryMapper.java
  api/src/main/java/com/org/gunbbang/util/mapper/MenuMapper.java
Labels: euna, FIX

#150 [FIX] 리뷰 작성하기 API 내에서 리뷰키워드 등록하는 로직 service 단에서 해결해라
  api/src/main/java/com/org/gunbbang/controller/ReviewsController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/util/ConstantVO.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: euna, FIX

#152 [FIX] 마이페이지 조회 API 회원 정보 가져오는 로직 수정 및 리팩터링해라
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/util/mapper/MemberTypeMapper.java
Labels: euna, FIX

#154 [FIX] 자체로그인 회원가입 api 수정
  api/src/main/java/com/org/gunbbang/AOP/ApiInfo/SignupApiInfo.java
  api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java
  api/src/main/java/com/org/gunbbang/AOP/logInfo/SignupLogInfo.java
  api/src/main/java/com/org/gunbbang/config/SecurityConfig.java
  api/src/main/java/com/org/gunbbang/controller/DTO/request/MemberSignUpRequestDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberSignUpResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewDetailResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewResponseDTO.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
  api/src/main/java/com/org/gunbbang/jwt/service/JwtService.java
  api/src/main/java/com/org/gunbbang/login/CustomUserDetails.java
  api/src/main/java/com/org/gunbbang/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  api/src/main/java/com/org/gunbbang/login/handler/LoginFailureHandler.java
  api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java
  api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java
  api/src/main/java/com/org/gunbbang/login/service/LoginService.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java
  api/src/main/java/com/org/gunbbang/util/mapper/MemberMapper.java
  api/src/main/java/com/org/gunbbang/util/security/SecurityUtil.java
  common/enum/src/main/java/com/org/gunbbang/MainPurpose.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/Member.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: seungha, FIX

#156 [FIX] ReviewService에서 리뷰 상세조회 시 추천 키워드 가져오는 로직은 함수를 사용하고 리턴 값에 Mapper 적용해라
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/util/mapper/RecommendKeywordMapper.java
  api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java
Labels: euna, FIX

#158 [FIX] 유저가 작성한 리뷰 빵집 정보를 기반으로 확인하는 API를 리팩터링해라
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/util/mapper/BakeryMapper.java
  api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java
Labels: euna, FIX

#160 [FEAT] 건빵집 리스트 조회 API 수정사항 반영하여 추가 기능 구현해라
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryCategoryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/resources/init/h2-data.sql
Labels: FEAT, euna

#161 [FEAT] 토큰 리프레시 기능 개발
  api/build.gradle
  api/src/main/java/com/org/gunbbang/common/dto/ApiResponse.java
  api/src/main/java/com/org/gunbbang/config/SecurityConfig.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java
  api/src/main/java/com/org/gunbbang/jwt/service/JwtService.java
  api/src/main/java/com/org/gunbbang/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.java
  api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java
  api/src/main/java/com/org/gunbbang/util/security/SecurityUtil.java
  common/exception/src/main/java/com/org/gunbbang/CustomJwtTokenException.java
  common/exception/src/main/java/com/org/gunbbang/UserNameNotFoundException.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
Labels: FEAT, seungha

#167 [FEAT] 자체로그인 로그아웃 기능 구현
  api/src/main/java/com/org/gunbbang/config/SecurityConfig.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java
  api/src/main/java/com/org/gunbbang/login/filter/JsonUsernamePasswordAuthenticationFilter.java
  api/src/main/java/com/org/gunbbang/login/handler/CustomLogoutHandler.java
  api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java
  api/src/main/java/com/org/gunbbang/login/handler/LogoutSuccessHandler.java
  api/src/main/java/com/org/gunbbang/util/security/SecurityUtil.java
Labels: FEAT, seungha

#169 [FIX] 베스트 컨텐츠 조회 api 수정
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: seungha, FIX

#173 [FIX] 필터칩 조회 및 필터칩 변경 api 수정
  .github/workflows/cd.yml
  .github/workflows/gradle.yml
  .gitignore
  api/src/main/java/com/org/gunbbang/controller/DTO/response/MemberTypeResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/response/ReviewReportResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/MemberController.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/util/mapper/MemberTypeMapper.java
  api/src/main/java/com/org/gunbbang/util/security/SecurityUtil.java
  storage/db-core/src/main/resources/init/h2-data.sql
  storage/db-core/src/main/resources/init/h2-schema.sql
Labels: seungha, FIX

#175 [FIX] 건빵집 리스트 조회에서 정렬 조건 제대로 인식되지 않는 문제 해결해라
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
Labels: euna, FIX
