Repository GEON-PPANG/GEON-PPANG-SERVER, pull requests merged in 2023-09, with the labels that each got.

#182 [FEAT] 소셜&자체 통합 회원탈퇴 로직 구현
  .github/workflows/cd.yml
  .github/workflows/gradle.yml
  api/build.gradle
  api/src/main/java/com/org/gunbbang/AOP/ApiInfo/RequestApiInfo.java
  api/src/main/java/com/org/gunbbang/GunbbangApplication.java
  api/src/main/java/com/org/gunbbang/controller/AuthController.java
  api/src/main/java/com/org/gunbbang/controller/DTO/FileDTO.java
  api/src/main/java/com/org/gunbbang/controller/DTO/FilesDTO.java
  api/src/main/java/com/org/gunbbang/controller/SearchController.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
  api/src/main/java/com/org/gunbbang/jwt/service/AppleJWTService.java
  api/src/main/java/com/org/gunbbang/jwt/service/JwtService.java
  api/src/main/java/com/org/gunbbang/login/CustomUserDetails.java
  api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java
  api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/support/advice/ApiControllerAdviser.java
  api/src/main/java/com/org/gunbbang/util/mapper/MemberMapper.java
  api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java
  client/client-feign/.gitignore
  client/client-feign/build.gradle
  client/client-feign/src/main/java/com/org/gunbbang/AppleFeignClient.java
  client/client-feign/src/main/java/com/org/gunbbang/FeignApplication.java
  client/client-feign/src/main/java/com/org/gunbbang/FeignConfig.java
  common/domain/src/main/java/com/org/gunbbang/DTO/BestReviewDTO.java
  common/domain/src/main/java/com/org/gunbbang/DTO/RevokeAppleTokenRequestDTO.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  settings.gradle
  storage/db-core/src/main/java/com/org/gunbbang/entity/Member.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: FEAT, seungha

#186 [FIX] 필터 선택 안한 회원도 베스트 리뷰 렌덤으로 조회되도록 수정하라
  api/src/main/java/com/org/gunbbang/AOP/ApiInfo/RequestApiInfo.java
  api/src/main/java/com/org/gunbbang/AOP/ApiInfo/SignupApiInfo.java
  api/src/main/java/com/org/gunbbang/AOP/LoggingAspect.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtAuthenticationProcessingFilter.java
  api/src/main/java/com/org/gunbbang/jwt/filter/JwtExceptionFilter.java
  api/src/main/java/com/org/gunbbang/jwt/service/AppleJwtService.java
  api/src/main/java/com/org/gunbbang/jwt/service/JwtService.java
  api/src/main/java/com/org/gunbbang/login/CustomUserDetails.java
  api/src/main/java/com/org/gunbbang/login/handler/LoginSuccessHandler.java
  api/src/main/java/com/org/gunbbang/login/service/CustomUserDetailsService.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  api/src/main/java/com/org/gunbbang/support/slack/SlackSender.java
  api/src/main/java/com/org/gunbbang/util/mapper/ReviewMapper.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: seungha, FIX

#187 [FIX] 애플로그인 시 request body에서 email 필드를 가져오도록 수정
  api/src/main/java/com/org/gunbbang/service/AppleAuthService.java
  api/src/main/java/com/org/gunbbang/service/NativeAuthService.java
  common/exception/src/main/java/com/org/gunbbang/BadRequestException.java
Labels: seungha, FIX

#188 [CHORE] @Valid 어노테이션 추가
  api/src/main/java/com/org/gunbbang/controller/AuthController.java
  api/src/main/java/com/org/gunbbang/controller/ValidationController.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: seungha, CHORE

#192 [FIX] 리뷰 텍스트가 빈문자열일 경우 베스트 리뷰 조회에서 제외되도록 설정
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: seungha, FIX

#194 [FIX] 별로에요인 리뷰에서 추천키워드가 함께 입력되면 에러를 반환해라
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
Labels: euna, FIX

#197 [FIX] 키워드 퍼센트 반환 시 특별해요 퍼센트 계산 인자를 수정해라
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
Labels: euna, FIX

#199 [FIX] 빵유형을 선택하지 않은 유저가 pesonalFilter true로 요청할 시에 대한 에러처리를 추가해라
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
Labels: euna, FIX

#201 [FIX] 좋아요 리뷰 작성 시 추천키워드 한개 이상 선택하지 않으면 에러를 반환해라
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
Labels: euna, FIX

#203 [FIX/#202] 이메일 중복체크 및 닉네임 중복체크 성공 시 response body 추가
  api/src/main/java/com/org/gunbbang/controller/DTO/response/ValidationResponseDTO.java
  api/src/main/java/com/org/gunbbang/controller/ValidationController.java
  api/src/main/java/com/org/gunbbang/service/MemberService.java
  common/exception/src/main/java/com/org/gunbbang/errorType/ErrorType.java
  common/exception/src/main/java/com/org/gunbbang/errorType/SuccessType.java
Labels: seungha, FIX

#204 [FIX] 소셜로그인 시 자동으로 지정되는 닉네임 이름에서 UUID 제외
  api/src/main/java/com/org/gunbbang/login/filter/JsonUsernamePasswordAuthenticationFilter.java
  api/src/main/java/com/org/gunbbang/service/AuthService.java
  api/src/main/java/com/org/gunbbang/service/AuthServiceProvider.java
Labels: seungha, FIX
