Repository GEON-PPANG/GEON-PPANG-SERVER, pull requests merged in 2024-02, with the labels that each got.

#270 [FEAT] 건빵집 리스트 페이지네이션 가능하도록 수정
  api/src/main/java/com/org/gunbbang/auth/security/util/SecurityUtil.java
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: FEAT, euna, FIX

#283 [FIX] 앰플리튜드 관련 안쓰는 기능 삭제
  api/src/main/java/com/org/gunbbang/service/AmplitudeService.java
Labels: seungha, FIX

#287 [FEAT] 필터칩을 선택하지 않은 유저가 건빵집 리스트에서 개인 맞춤 필터를 사용하려고 하는 경우에 대한 예외 처리 구현
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
Labels: FEAT, euna

#295 엑세스 토큰 없이 회원탈퇴 요청 시 401 에러, 엑세스 토큰 없이 로그아웃 요청 시 400에러 떨어지도록 변경
  api/src/main/java/com/org/gunbbang/auth/jwt/service/JwtService.java
  api/src/main/java/com/org/gunbbang/auth/security/config/SecurityConfig.java
  api/src/main/java/com/org/gunbbang/auth/security/handler/CustomLogoutHandler.java
  api/src/main/java/com/org/gunbbang/service/AmplitudeService.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
Labels: seungha, FIX

#296 [FIX] 건빵집 리스트에서 사용되는 쿼리에서 left 조인을 inner 조인으로 변경
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: euna, FIX

#299 베스트 빵집 및 베스트 리뷰 조회 시 버그 발생 해결
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  api/src/main/java/com/org/gunbbang/service/ReviewService.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryBreadType.java
  storage/db-core/src/main/java/com/org/gunbbang/entity/BakeryNutrientType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BookMarkRepository.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/ReviewRepository.java
Labels: seungha, FIX

#302 [HOTFIX] 빵유형 일치 베이커리 중복조회되는 버그 해결
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: seungha, hotfix

#303 [HOTFIX] 건빵집 리스트 중복 문제 해결(드디어..)
  api/src/main/java/com/org/gunbbang/controller/BakeriesController.java
  api/src/main/java/com/org/gunbbang/service/BakeryListService.java
  api/src/main/java/com/org/gunbbang/service/BakeryService.java
  common/enum/src/main/java/com/org/gunbbang/CategoryType.java
  storage/db-core/src/main/java/com/org/gunbbang/repository/BakeryRepository.java
Labels: euna, hotfix
